# Generated by Django 3.2.12 on 2022-08-25 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submetido'), ('enqueued-for-validation', 'Enqueued for validation'), ('validated-with-errors', 'Validated with errors'), ('validated-without-errors', 'Validated without errors'), ('pending-correction', 'Pending for correction'), ('ready-to-be-finished', 'Ready to be finished'), ('quality-analysis', 'Waiting for quality analysis'), ('rejected', 'Rejeitado'), ('accepted', 'Accepted'), ('scheduled-for-publication', 'Scheduled for publication'), ('published', 'Publicado')], default='enqueued-for-validation', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='validationerror',
            name='category',
            field=models.CharField(choices=[('package-file-error', 'PACKAGE_FILE_ERROR'), ('xml-format-error', 'XML_FORMAT_ERROR'), ('bibliometrics-data-error', 'BIBLIOMETRICS_DATA_ERROR'), ('services-data-error', 'SERVICES_DATA_ERROR'), ('data-consistency-error', 'DATA_CONSISTENCY_ERROR'), ('criteria-issues', 'CRITERIA_ISSUES'), ('asset-error', 'ASSET_ERROR'), ('rendition-error', 'RENDITION_ERROR')], max_length=32, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='validationerror',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ErrorResolution',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('validation_error', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resolution', serialize=False, to='upload.validationerror')),
                ('action', models.CharField(blank=True, choices=[('to-fix', 'I will fix this error'), ('disagree', 'This is not an error'), ('unknow', 'I do not know how to fix this error')], max_length=32, null=True, verbose_name='Action')),
                ('comment', models.TextField(blank=True, max_length=512, null=True, verbose_name='Comment')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='errorresolution_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errorresolution_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
