# Generated by Django 3.2.12 on 2022-08-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_validationerror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationerror',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='validationerror',
            name='snippet',
        ),
        migrations.AddField(
            model_name='validationerror',
            name='message',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submetido'), ('enqueued-for-validation', 'Enqueued for validation'), ('validated-with-errors', 'Validated with errors'), ('validated-without-errors', 'Validated without errors'), ('rejected', 'Rejeitado'), ('accepted', 'Accepted'), ('scheduled-for-publication', 'Scheduled for publication'), ('published', 'Publicado')], default='enqueued-for-validation', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='validationerror',
            name='category',
            field=models.CharField(choices=[('package-file-error', 'PACKAGE_FILE_ERROR'), ('xml-format-error', 'XML_FORMAT_ERROR'), ('bibliometrics-data-error', 'BIBLIOMETRICS_DATA_ERROR'), ('services-data-error', 'SERVICES_DATA_ERROR'), ('data-consistency_error', 'DATA_CONSISTENCY_ERROR'), ('criteria-issues', 'CRITERIA_ISSUES')], max_length=32, verbose_name='Category'),
        ),
    ]
